esphome:
  name: ${id}
  platform: ESP8266
  board: ${board}
  esp8266_restore_from_flash: true

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  power_save_mode: none

#api:

logger:

ota:

web_server:
  port: 80

# Enable getting local time for total daily energy calculation
time:
- platform: sntp
  id: sntp_time
  timezone: !secret site_tz
#- platform: homeassistant
#  id: homeassistant_time
#  timezone: !secret site_tz

text_sensor:
- platform: version
  name: "${id} ESPHome version"

mqtt:
  broker: !secret mqtt_ip
  port: !secret mqtt_port
  username: !secret mqtt_username
  password: !secret mqtt_password
