<<: !include chip.esp8266.yaml
<<: !include common.yaml
sensor: !include_dir_merge_list gosund.wp3.sensor

status_led:
  pin:
    number: GPIO12
    inverted: true

switch:
  - platform: gpio
    id: led2
    pin:
      number: GPIO13
      inverted: true
  - platform: gpio
    name: "${display_name}"
    pin: GPIO14
    id: relay
    restore_mode: "${relay_restore}"
    on_turn_on:
    - switch.turn_on: led2
    on_turn_off:
    - switch.turn_off: led2

binary_sensor:
  - platform: gpio
    pin:
      number: GPIO4
      mode: INPUT_PULLUP
      inverted: true
    name: "${display_name} Button"
    on_press:
      - switch.toggle: relay
    internal: true
