<<: !include chip.esp32.yaml
<<: !include common.yaml
sensor: !include_dir_merge_list lilygo.t-higrowv1.1.sensor

i2c:
  sda: 25
  scl: 26
  scan: True
  id: bus_a
  setup_priority: -200

switch:
- platform: gpio
  pin: 4
  name: "enable_sensors"
  restore_mode: ALWAYS_ON
  internal: true
  setup_priority: 1000

binary_sensor:
  - platform: gpio
    pin: 
      number: GPIO35
      mode: INPUT_PULLUP
      inverted: True
    name: "${display_name} Button"
    internal: true
