<<: !include chip.esp8266.yaml
<<: !include common.yaml
sensor: !include_dir_merge_list sonoff.basic.sensor

# sonoff1-pending.yaml
#substitutions:
#  id: sonoff2
#  plug_type: sonoff.basic
#  board: esp01_1m
#  display_name: "Sonoff1-Basic"
#  relay_restore: "RESTORE_DEFAULT_OFF"
#<<: !include "esphome_templates/sonoff.basic.yaml"

captive_portal:

status_led:
  pin:
    number: GPIO13
    inverted: true

switch:
  - platform: gpio
    name: "${display_name}"
    pin: GPIO12
    id: relay
    restore_mode: "${relay_restore}"

binary_sensor:
  - platform: gpio
    pin:
      number: GPIO0
      mode: INPUT_PULLUP
      inverted: true
    name: "${display_name} Button"
    on_press:
      - switch.toggle: relay
    internal: true
