<<: !include chip.esp8266.yaml
<<: !include common.yaml
sensor: !include_dir_merge_list wemos.d1_mini.sensor

# Generic just to put device on the wifi

# wemos1-pending.yaml
#substitutions:
#  id: wemos1
#  plug_type: wemos.d1_mini
#  board: d1_mini
#  display_name: "wemos1"
#<<: !include "esphome_templates/wemos.d1_mini.garagedoor.yaml"

# Relay to trip the garage door
# wemos 5v <-> relay +
# wemos gnd <-> relay -
# wemos D1 <-> relay S
switch:
- platform: gpio
  pin: D1
  id: relay
  restore_mode: "ALWAYS_OFF"

# Some form of button to detect if garagedoor is closed
# wemos 3v3 -> switch
# switch -> 10k Ohm Resistor -> wemos gnd
# switch -> wemos D5
# Shortcut: I soldered a 10k Ohm Resister directly between Wemos D5 and Wemos GND, this allows direct bridging of D5 and 3v3 with the switch
binary_sensor:
- platform: gpio
  pin: D5
  id: endstop_close

cover:
- platform: template
  name: "${display_name}"
  device_class: garage
  optimistic: false
  has_position: false

  lambda: !lambda |-
      if (id(endstop_close).state) {
        return COVER_CLOSED;
      } else {
        return COVER_OPEN;
      }

  open_action:
  - switch.turn_on: relay
  - delay: 0.1s
  - switch.turn_off: relay

  close_action:
  - switch.turn_on: relay
  - delay: 0.1s
  - switch.turn_off: relay
