- platform: adc
  pin: GPIO32
  name: "${display_name} Soil Moisture"
  update_interval: 60s
#  unit_of_measurement: '%'
#  filters:
#  - calibrate_linear:
#    # Map 0.0 (from sensor) to 0.0 (true value)
#    - 1.1 -> 0.0
#    - 0.0 -> 100.0
