- platform: dht
  model: DHT11
  pin: GPIO16
  temperature:
    name: "${display_name} Temperature"
    filters:
    - lambda: return x * (9.0/5.0) + 32.0;
    unit_of_measurement: "°F"
  humidity:
    name: "${display_name} Humidity"
  update_interval: 60s
  setup_priority: -100
